package:
  name: bats
  version: 1.11.0
  epoch: 2
  description: Bash Automated Testing System
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - bash
      - coreutils
      - ncurses
      - parallel

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - wget

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bats-core/bats-core
      tag: v${{package.version}}
      expected-commit: 5da66876b8b619235aee1eb3e54954eaca88059b

  - runs: |
      ./install.sh "${{targets.contextdir}}/usr"
      mkdir -p "${{targets.contextdir}}/tmp/"
      mv ./docker "${{targets.contextdir}}/tmp/docker"
      ls -la "${{targets.contextdir}}/tmp/docker/"
      "${{targets.contextdir}}/tmp/docker/install_libs.sh" support 0.3.0
      "${{targets.contextdir}}/tmp/docker/install_libs.sh" file 0.4.0
      "${{targets.contextdir}}/tmp/docker/install_libs.sh" assert 2.1.0
      "${{targets.contextdir}}/tmp/docker/install_libs.sh" detik 1.3.1
      mkdir -p "${{targets.contextdir}}/usr/local/bin"
      ln -s /opt/bats/bin/bats "${{targets.contextdir}}/usr/local/bin/bats"
      find "${{targets.contextdir}}" -type f -perm /2000 -exec chmod g-s {} \;
      rm -rf "${{targets.contextdir}}/tmp/"

subpackages:
  - name: bats-compat
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}/opt/bats/"
          find . -maxdepth 1 -not -name '.' -not -name 'melange-out' -not -name '*.tmp' -not -name '*.log' \
            -exec mv {} "${{targets.contextdir}}/opt/bats/" \;
    description: bats compatibility package

  - name: bats-doc
    pipeline:
      - uses: split/manpages
    description: bats manpages

update:
  enabled: true
  github:
    identifier: bats-core/bats-core
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        bats --version
