package:
  name: hydra
  version: 2.3.0
  epoch: 0
  description: OpenID Certified OAuth 2.0 Server and OpenID Connect Provider
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "1" # Needed for SQLite support

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ory/hydra
      tag: v${{package.version}}
      expected-commit: ee8c339ddada3a42529c0416897abc32bad03bbb

  - uses: go/install
    with:
      package: .
      ldflags: -X 'github.com/ory/hydra/v2/driver/config.Version=$(git describe --abbrev=0 --tags)' -X 'github.com/ory/hydra/v2/driver/config.Date=$(TZ=UTC date -u "+%Y-%m-%dT%H:%M:%SZ")' -X 'github.com/ory/hydra/v2/driver/config.Commit=$(git rev-parse HEAD)'
      tags: sqlite,json1,hsm

  - runs: |
      mkdir -p "${{targets.destdir}}/usr/local/bin"
      cp /home/build/melange-out/${{package.name}}/usr/bin/hydra "${{targets.destdir}}"/usr/local/bin/hydra

update:
  enabled: true
  github:
    identifier: ory/hydra
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - curl
  pipeline:
    - runs: |
        set -ex
        /usr/local/bin/hydra version
        /usr/local/bin/hydra help
        export DSN=memory
        /usr/local/bin/hydra migrate sql up -e --yes
        /usr/local/bin/hydra serve all --dev &
        sleep 5
        curl -s http://localhost:4444/health/alive | grep '"status":"ok"'
