package:
  name: mysqld_exporter
  version: "0.15.1"
  epoch: 1
  description: Prometheus exporter for MySQL server metrics.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/mysqld_exporter
      tag: v${{package.version}}
      expected-commit: cc349684494b5038ec5a52233bdca9eb9291e6f2

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0 golang.org/x/net@v0.23.0
      modroot: .

  - uses: go/build
    with:
      modroot: .
      packages: .
      output: mysqld-exporter
      ldflags: -s -w -X 'github.com/prometheus/mysqld_exporter/version.Version=${{package.version}}'

  - runs: |
      mkdir -p "${{targets.destdir}}"/opt/bitnami/mysqld-exporter/bin/
      mv mysqld-exporter "${{targets.destdir}}"/opt/bitnami/mysqld-exporter/bin/
      ln -sf ${{targets.destdir}}/opt/bitnami/mysqld-exporter/bin/mysqld_exporter ${{targets.destdir}}/bin/mysqld_exporter

  - uses: strip

subpackages:
  - name: mysqld-exporter-bitnami-compat
    description: "compat package with bitnami/mysqld-exporter image"
    pipeline:
      - uses: bitnami/compat
        with:
          image: mysqld-exporter
          version-path: 0/debian-12

update:
  enabled: true
  github:
    identifier: prometheus/mysqld_exporter
    strip-prefix: v

test:
  environment:
    environment:
      # Skip MySQL specific environment variables
  pipeline:
    - name: "Test --help"
      runs: |
        mysqld_exporter --help || (echo "Help command failed!" && exit 1)
    - name: "Test MySQL Exporter start without connection"
      runs: |
        mysqld_exporter --version > /tmp/mysqld-exporter.log 2>&1 &
        sleep 5
        # Check logs for expected output (without MySQL connection)
        if grep -q "mysqld_exporter" /tmp/mysqld-exporter.log; then
          echo "Test passed: mysqld_exporter started successfully."
        else
          echo "Test failed: mysqld_exporter did not start successfully."
          cat /tmp/mysqld-exporter.log
          exit 1
        fi

